name: New York Train
description: |
  You are on the last train. The Grinch threats are making you worried. You want to access
  the loan applications. At the same time, you are wondering whether it is safe to navigate
  personal and financial data on the train. You are tired and have only one thought:
  1 - Given the attack threat, it is important to view reports on the train.
  2 - Confidential data cannot be accessed in public spaces.
  3 - The Grinch has eyes everywhere and there is no point in being discreet or worried,
  since he can access any data at any time.

  (enter the number of the option you think is correct)

  You can check your current location using: map
  You can provide feedback on this room using: feedback input